[package]
name = "miremote-desktop"
version = "0.1.0"
description = "小米蓝牙语音遥控器跨平台控制面板"
authors = ["zyk"]
edition = "2021"
rust-version = "1.77"

[lib]
name = "miremote_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.24", features = ["native-tls"] }
futures-util = "0.3"
anyhow = "1"
thiserror = "1"
dirs = "5"
flate2 = "1"
tauri-plugin-single-instance = "2.0.0-rc.5"

[profile.release]
opt-level = "s"
lto = true
strip = true
codegen-units = 1
